### ISSUE TITLE
beta.js sourcecode is obfuscated

### ISSUE THREAD

**Issue by nderscore** [sinfulBA/DubX-Script#1]
For an open-source project, this is pretty sketchy.

**Comment by sinfulBA** [comment]
Hey nderscore. Dub X is not open source. The site itself is however. Here is the github link: https://github.com/dubtrack/www-dubtrack-fm

**Comment by nderscore** [comment]
Why host the project in a public github? You're not really gaining any of the benefits of using version control if you're committing obfuscated code.

**Comment by sinfulBA** [comment]
This isn't the main hosting of the github. This is just the publicized code. Our main github project for Dub X is private and worked on by only a few people.

**Comment by Gbear605** [comment]
The project has now been deobfuscated, so this issue can be closed.

**Comment by sinfulBA** [comment]
We've released our first Version, thus removing the obfuscation and adding a new LICENSE.

**Comment by swordling** [comment]
Closed.
