### ISSUE TITLE
You can't load DubX due to a new Content Security Policy

### ISSUE THREAD

**Issue by Gbear605** [sinfulBA/DubX-Script#2]
You can't load the DubX script on any new pages on dubtrack.fm, due to a new Content Security Policy they have. If you try, the console says

Refused to load the script 'https://rawgit.com/sinfulBA/DubX-Script/master/beta.js?_=1443870846716' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.pubnub.com https://use.typekit.net https://content.jwplatform.com https://www.google.com https://mediadubtrackfm.s3.amazonaws.com https://cdn.pubnub.com https://www.google.com https://content.jwplatform.com https://use.typekit.net https://ssl.google-analytics.com/ga.js https://*.youtube.com *.ytimg.com *.jwpsrv.com *.jwpcdn.com".

The only possible solution I know of (since you can't disable a Content Security Policy safely, and you definitely shouldn't have all of your users disable it) is to give all the source code locally, so the bookmarklet isn't loading any off-site code. This is obviously essentially impossible with a bookmarklet, since they would have to update the bookmarklet anytime  you update, plus the obvious problems with having a bookmarklet that long (does Chrome even support ones that long?). The other solution is to do the same thing, but with the extension on the Chrome Store, which is feasible, since it autoupdates (see this page: https://www.quora.com/Are-there-any-ways-to-push-an-auto-update-for-a-Chrome-extension), but forces everyone to use your extension.

**Comment by Gbear605** [comment]
Note: it still works in Internet Explorer, as shown at http://caniuse.com/#feat=contentsecuritypolicy

**Comment by Gbear605** [comment]
Multiple users in my room is reporting that it still works for them in Opera. However, this may be due to their caches not updating.

**Comment by pootato** [comment]
It's broken in Chrome, go back a version you fucked up.

**Comment by sinfulBA** [comment]
Please stop commenting on this. It is not our fault. Dubtrack introduced a Content-Security Policy that requires sites that host third-party scripts to be white-listed. If anyone even checked the error when trying to submit the code they would see it themselves.

Thank you Gbear605 for your info, I have been talking to the Dubtrack dev all day for getting my repository white-listed.

**Comment by pootato** [comment]
Smart move by Dubtrack, anyone can make a harmful script and pass it off as an addon.

**Comment by sinfulBA** [comment]
That's what happened. Someone injected HTML that redirected users to another site through javascript. They're trying to prevent that, but it's a sloppy way.

**Comment by pootato** [comment]
Is there any workaround for this until DubX gets whitelisted?

**Comment by sinfulBA** [comment]
If you just copy the code and paste it, it should work for the most part.
https://rawgit.com/sinfulBA/DubX-Script/master/beta.js

**Comment by swordling** [comment]
Check yourself before you rekt yourself next time please.

**Comment by Fuechschen** [comment]
Even the option to paste the code in the js console isn't possible due to dependecies dubx is loading from rawgit: https://share.fuechschen.org/data/2015/10/2015-10-04_23-25-33.jpg

So, why don't you use cloudflare as CDN and deliver the script over your dubx.net domain because this domain is whitelisted. Cloudflare performs great as CDN if you set the caching option to "Cache everything" through a page rule.

**Comment by Gbear605** [comment]
This is a nonissue now, as Dubtrack has decided to remove the Content Security Policy.
