### ISSUE TITLE
Auto-clear Chat Feature

### ISSUE THREAD

**Issue by poomato** [sinfulBA/DubX-Script#28]
Set a button to enable the following code to clear chat every 30 minutes.

window.setInterval(function(){
$('.clearChatToggle').click();
}, 1500000);

Grow a dick Swordling.

**Comment by swordling** [comment]
We don't like your feature. End of story.

**Comment by sinfulBA** [comment]
Sigh. This is sinful, can you please come to http://dubtrack,fm/join/dubx so I can talk about it?

**Comment by poomato** [comment]
Tell that to Plug.dj, who had it implemented by default.

**Comment by swordling** [comment]
Go create an issue on Dubtrack's Github then. Leave us the fuck alone.

**Comment by poomato** [comment]
Are you out of Menu space? There's no reason to deny this simple feature.

**Comment by swordling** [comment]
I'm out of patience.

**Comment by poomato** [comment]
You have spacebar mute but can't implement this? Talk about useless features.

**Comment by sinfulBA** [comment]
Come to https://dubtrack.fm/join/dubx please. I will explain to you why we don't want to add the feature. 

-sinful

**Comment by poomato** [comment]
Just answer here and close it.

**Comment by swordling** [comment]
Because a lot of people requested spacebar mute.

**Comment by sinfulBA** [comment]
If you do not come to the room, I will not answer you and I will ignore you. I don't have patience to talk via GitHub.

-sinful

**Comment by swordling** [comment]
We didn't want to add it originally, but the requests were overwhelming so we decided to.

**Comment by poomato** [comment]
Hahah give me a break. We can't implement it because WE don't want it.

**Comment by swordling** [comment]
We don't want to be RCS - so bloated with horrible features that the script failed to load half the time. If you don't agree with how we run our script then go make your own.

**Comment by sinfulBA** [comment]
There's a bigger reason why. If you like to hear it, come to the room, otherwise do not comment.

**Comment by poomato** [comment]
So bloated with a 3 line code? Give me a break.

**Comment by swordling** [comment]
You also need to know how to not act like a child when something doesn't go your way.
