### ISSUE TITLE
Implement loader for custom scripts

### ISSUE THREAD

**Issue by Fuechschen** [sinfulBA/DubX-Script#30]
So, i totally understand you want to make your script as lightweight as possible, but there are still people who will demand features you don't want to add. So why aren't you adding a loader for script with an simple API for the your GUI. 
People who are like the simple version are able to use it, but if someone's like to have more features, he can simply add other scripts without having to load multiple bookmarks everytime he opens dubtrack.

**Comment by sinfulBA** [comment]
Hmm, I'm not really interested in having those things part of our script. We appreciate your idea.
