### ISSUE TITLE
Emoji One

### ISSUE THREAD

**Issue by ChipWolf** [sinfulBA/DubX-Script#57]
A nice addition would be if you could add an option to swap out the dubtrack.fm's iPhone emoji set with the Emoji One set from http://emojione.com/

![](http://emojione.com/wp-content/themes/emojione.v2/images/vectors/emojis/1f61d.svg)

Great work nonetheless!

**Comment by sinfulBA** [comment]
Thank you for the suggestion, but we'll keep the emoji-sheet Dubtrack uses. :)

**Comment by ChipWolf** [comment]
Noted, forwarded suggestion to Dubtrack, forking for my own implementation.
