### ISSUE TITLE
Chrome Extension link doesn't work

### ISSUE THREAD

**Issue by Fuechschen** [sinfulBA/DubX-Script#73]
Well, i don't know if I'm just an idiot who's having the wrong link, but I'm unable to find the extension in the chrome webstore, the url on the website just shows me this: http://i.imgur.com/LSmq3wr.png

**Comment by Netox005** [comment]
Google took DubX out of the Chrome Web Store for some reason. Swordling said they already reuploaded and are waiting for Google to approve it.
You can still download Tampermonkey, which is the Chrome alternative from Greasemonkey on Firefox and use the UserScript.

**Comment by gempir** [comment]
Any update on this? anything but the chrome extension is just annoying to use

**Comment by PossiblyKris** [comment]
Chrome extension is back as of March 29.
