### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Pik-achu** [sinfulBA/DubX-Script#79]
Dubx has stopped working for some reason.

**Comment by PossiblyKris** [comment]
The server we host it on (rawgit.com) is down right now unfortunately, it should be up very soon hopefully, or we'll change figure something out.

**Comment by coryshaw1** [comment]
rgrove/rawgit#108

**Comment by coryshaw1** [comment]
Rawgit is back up, sorry for the downtime!
