### ISSUE TITLE
Community theme not working

### ISSUE THREAD

**Issue by Hardatyou** [sinfulBA/DubX-Script#84]
We try putting the CSS link under the info or at the start, even if we deleted everything else and leave only the link in the "info" section. But it still doesnt work. I'm pretty sure the problem is not from our side.

**Comment by coryshaw1** [comment]
It it like this?

`@dubx=http://yourstylesheet.com/style.css`

It needs to be on its own line of your room info panel, and you must include `@dubx=` at the beginning of the stylesheet url without spaces.

**Comment by Hardatyou** [comment]
Works great!

**Comment by coryshaw1** [comment]
Glad to hear it! 

I'm going to go ahead and close this issue. Feel free to reopen if you continue to have issues related to this.
