### ISSUE TITLE
asset.css problem

### ISSUE THREAD

**Issue by dorkix** [sinfulBA/DubX-Script#87]
Since the latest dubtrack update there seems to be a problem with asset.css. It shows double ranks. Here is the picture of the problem http://s33.postimg.org/4sfvn6e27/123.png . Problem seems to lie on lines 443-465. Don't know if you are gonna wait until rest of the dubtrack updates are finished but it would be appreciated if you could quickly sort it out.

**Comment by FranciscoG** [comment]
nice catch!

I just pushed a fix so it should be good now.  Let me know if you continue to see any issues related to this.  If all good then I'll close this issue

**Comment by dorkix** [comment]
Seems like everything is in order. Thanks for the quick response!
