### ISSUE TITLE
Bug report doesn't work

### ISSUE THREAD

**Issue by rinu** [sinfulBA/DubX-Script#92]
DubX has a Bug report feature but clicking Okay gives an error like
    Uncaught TypeError: Cannot read property 'get_uuid' of undefined

What I was going to report is that it doesn't work when I'm not logged in.
And that it doesn't work on Opera using the Chrome extension, only copy-pasting the whole source works.

**Comment by coryshaw1** [comment]
This has been fixed! Thanks for letting us know
